import { MatchDetails } from '../../models/match-details';

export const SampleData: MatchDetails = {
    Heroes: [
        'Orphea',
        'Azmodan',
        'TheLostVikings',
        'Muradin',
        'Malfurion',
        'Johanna',
        'Raynor',
        'Chromie',
        'Sonya',
        'Ana',
        'LostVikingsController',
        'Olaf',
        'Baleog',
        'Erik',
        'Crusader',
        'Barbarian'
    ],
    TeamObjectiveNames: [
        'FirstCatapultSpawn1'
    ],
    TeamObjectiveImages: [
        '/Images/Awards/1MVP.png'
    ],
    XValues: [
        780
    ],
    YValues: [
        0
    ],
    XHeroDeaths: [
        90,
        135,
        180,
        225,
        225,
        270,
        315,
        315,
        315,
        315,
        360,
        405,
        405,
        405,
        450,
        495,
        495,
        495,
        540,
        540,
        540,
        540,
        540,
        630,
        630,
        630,
        630,
        675,
        720,
        720,
        720,
        810
    ],
    YHeroDeaths: [
        4600,
        4600,
        4600,
        -4600,
        4600,
        -4600,
        -4600,
        4600,
        3725,
        2850,
        4600,
        -4600,
        -3725,
        -2850,
        -4600,
        4600,
        3725,
        2850,
        -4600,
        -3725,
        -2850,
        4600,
        3725,
        4600,
        3725,
        -4600,
        -3725,
        4600,
        4600,
        3725,
        2850,
        4600
    ],
    XDiff: [
        0,
        98,
        158,
        218,
        278,
        338,
        398,
        458,
        518,
        578,
        638,
        698,
        758,
        818,
        878,
        882
    ],
    YDiff: [
        0,
        240,
        -116,
        -210,
        -635,
        1429,
        -367,
        3512,
        2768,
        393,
        1509,
        3923,
        1748,
        -628,
        1080,
        1080
    ],
    MatchEventTimers: [
        790
    ],
    DeathTimers: [
        114,
        169,
        224,
        228,
        252,
        295,
        333,
        339,
        342,
        352,
        385,
        411,
        435,
        440,
        457,
        503,
        515,
        537,
        563,
        576,
        579,
        572,
        576,
        658,
        672,
        665,
        667,
        677,
        729,
        736,
        747,
        818
    ],
    EventLabels: [
        'First Catapult Spawn'
    ],
    DeathLabels: [
        'Orphea (YOAV) killed by Raynor (front)',
        'The Lost Vikings (Titan) killed by Sonya (Shaku)',
        'The Lost Vikings (Titan) killed by Sonya (Shaku)',
        'Chromie (TommyLee) killed by Orphea (YOAV)',
        'The Lost Vikings (Titan) killed by Sonya (Shaku)',
        'Johanna (Kresko) killed by Malfurion (Skywalker)',
        'Raynor (front) killed by Orphea (YOAV)',
        'Orphea (YOAV) killed by Chromie (TommyLee)',
        'The Lost Vikings (Titan) killed by Sonya (Shaku)',
        'Muradin (PortgasDAce) killed by Chromie (TommyLee)',
        'The Lost Vikings (Titan) killed by Sonya (Shaku)',
        'Raynor (front) killed by Orphea (YOAV)',
        'Chromie (TommyLee) killed by The Lost Vikings (Titan)',
        'Johanna (Kresko) killed by The Lost Vikings (Titan)',
        'Sonya (Shaku) killed by Azmodan (ImANinja)',
        'The Lost Vikings (Titan) killed by TownCannonTowerL2',
        'Orphea (YOAV) killed by RangedMinion',
        'Azmodan (ImANinja) killed by Raynor (front)',
        'Ana (Wrinkle) killed by Orphea (YOAV)',
        'Raynor (front) killed by The Lost Vikings (Titan)',
        'Johanna (Kresko) killed by The Lost Vikings (Titan)',
        'Orphea (YOAV) killed by Chromie (TommyLee)',
        'Malfurion (Skywalker) killed by Chromie (TommyLee)',
        'Malfurion (Skywalker) killed by Raynor (front)',
        'The Lost Vikings (Titan) killed by Sonya (Shaku)',
        'Johanna (Kresko) killed by Orphea (YOAV)',
        'Raynor (front) killed by The Lost Vikings (Titan)',
        'The Lost Vikings (Titan) killed by Sonya (Shaku)',
        'The Lost Vikings (Titan) killed by Chromie (TommyLee)',
        'Orphea (YOAV) killed by Johanna (Kresko)',
        'Malfurion (Skywalker) killed by Johanna (Kresko)',
        'The Lost Vikings (Titan) killed by Sonya (Shaku)'
    ],
    MaxXpDifference: 5000,
    TeamObjectiveStyles: [
        'FirstCatapultSpawn1'
    ],
    HeroDeathStyles: [
        'heroOrphea',
        'heroTheLostVikings',
        'heroTheLostVikings',
        'heroChromie',
        'heroTheLostVikings',
        'heroJohanna',
        'heroRaynor',
        'heroOrphea',
        'heroTheLostVikings',
        'heroMuradin',
        'heroTheLostVikings',
        'heroRaynor',
        'heroChromie',
        'heroJohanna',
        'heroSonya',
        'heroTheLostVikings',
        'heroOrphea',
        'heroAzmodan',
        'heroAna',
        'heroRaynor',
        'heroJohanna',
        'heroOrphea',
        'heroMalfurion',
        'heroMalfurion',
        'heroTheLostVikings',
        'heroJohanna',
        'heroRaynor',
        'heroTheLostVikings',
        'heroTheLostVikings',
        'heroOrphea',
        'heroMalfurion',
        'heroTheLostVikings'
    ],
    MaxXpDiffTick: 892,
};