create table slice_replayids select distinct replayid from replay where timestampreplay>='2022-04-01';
create table slice_playerids select distinct playerid from replaycharacter where replayid in (select * from slice_replayids);
insert into slice_playerids select distinct playerid from net48_users where playerid not in (select * from slice_playerids);
create table slice_localizationalias select * from localizationalias;
create table slice_league select * from league;
create table slice_buildnumbers select * from buildnumbers;
create table slice_heroiconinformation select * from heroiconinformation;
create table slice_herotalentinformation select * from herotalentinformation;
create table slice_talentimagemapping select * from talentimagemapping;
create table slice_player select * from player where playerid in (select * from slice_playerids);
create table slice_net48_users select * from net48_users;
create table slice_replay select * from replay where replayid in (select * from slice_replayids);
create table slice_replaycharacter select * from replaycharacter where replayid in (select * from slice_replayids);
create table slice_event select * from `event`;
create table slice_event_team select * from event_team;
create table slice_leaderboardoptout select * from leaderboardoptout where playerid in (select * from slice_playerids);
create table slice_leaderboardranking select * from leaderboardranking where playerid in (select * from slice_playerids);
create table slice_playeraggregate select * from playeraggregate where playerid in (select * from slice_playerids);
create table slice_playeralt select * from playeralt where playeridalt in (select * from slice_playerids) and playeridmain in (select * from slice_playerids);
create table slice_playerbanned select * from playerbanned where playerid in (select * from slice_playerids);
create table slice_playerdisablenamechange select * from playerdisablenamechange where playerid in (select * from slice_playerids);
create table slice_playermmrmilestonev3 select * from playermmrmilestonev3 where playerid in (select * from slice_playerids) and MilestoneDate>='2022-04-01';
create table slice_playermmrreset select * from playermmrreset;
create table slice_replay_mirror select * from replay_mirror where replayid in (select * from slice_replayids);
create table slice_replay_notalents select * from replay_notalents where replayid in (select * from slice_replayids);
create table slice_replay_playertalentbuilds select * from replay_playertalentbuilds where replayid in (select * from slice_replayids);
create table slice_replaycharacter_pro_association select * from replaycharacter_pro_association where replayid in (select * from slice_replayids);
create table slice_replaycharacterdraftorder select * from replaycharacterdraftorder where replayid in (select * from slice_replayids);
create table slice_replaycharactermatchaward select * from replaycharactermatchaward where replayid in (select * from slice_replayids);
create table slice_replaycharacterscoreresult select * from replaycharacterscoreresult where replayid in (select * from slice_replayids);
create table slice_replaycharactertalent select * from replaycharactertalent where replayid in (select * from slice_replayids);
create table slice_replaycharacterupgradeeventreplaylengthpercent select * from replaycharacterupgradeeventreplaylengthpercent where replayid in (select * from slice_replayids);
create table slice_replayperiodicxpbreakdown select * from replayperiodicxpbreakdown where replayid in (select * from slice_replayids);
create table slice_replayteamheroban select * from replayteamheroban where replayid in (select * from slice_replayids);
create table slice_replayteamobjective select * from replayteamobjective where replayid in (select * from slice_replayids);
create table slice_reputation select * from reputation where playerid in (select * from slice_playerids);
create table slice_votes select * from votes where targetreplayid in (select * from slice_replayids) and votingplayerid in (select * from slice_playerids) and targetplayerid in (select * from slice_playerids);
