// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Heroes.DataAccessLayer.Models
{
    [Table("amazonreplacementbucket")]
    public partial class AmazonReplacementBucket
    {
        [Key]
        [Column(TypeName = "varchar(200)")]
        public string Id { get; set; }
        public byte[] Blob { get; set; }
    }
}