// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Heroes.DataAccessLayer.Models
{
    [Table("buildnumbers")]
    public partial class BuildNumber
    {
        [Key]
        [Column("buildnumber", TypeName = "int(11)")]
        public int Buildnumber1 { get; set; }
        [Column("builddate", TypeName = "date")]
        public DateTime? Builddate { get; set; }
        [Column("version", TypeName = "varchar(45)")]
        public string Version { get; set; }
    }
}