// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Heroes.DataAccessLayer.Models
{
    [Table("dataupdate")]
    public partial class DataUpdate
    {
        [Key]
        [Column(TypeName = "varchar(100)")]
        public string DataEvent { get; set; }
        [Column(TypeName = "timestamp")]
        public DateTime LastUpdated { get; set; }
    }
}