// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Heroes.DataAccessLayer.Models
{
    [Table("event")]
    public partial class Event
    {
        public Event()
        {
            InverseEventIdparentNavigation = new HashSet<Event>();
            Teams = new HashSet<EventTeam>();
        }

        [Key]
        [Column("EventID", TypeName = "int(11)")]
        public int EventId { get; set; }
        [Column("EventIDParent", TypeName = "int(11)")]
        public int? EventIdparent { get; set; }
        [Required]
        [Column(TypeName = "varchar(100)")]
        public string EventName { get; set; }
        [Column(TypeName = "int(11)")]
        public int EventOrder { get; set; }
        [Column(TypeName = "int(11)")]
        public int EventGamesPlayed { get; set; }
        [Column(TypeName = "bit(1)")]
        public ulong IsEnabled { get; set; }

        [ForeignKey(nameof(EventIdparent))]
        [InverseProperty(nameof(Event.InverseEventIdparentNavigation))]
        public virtual Event EventIdparentNavigation { get; set; }
        [InverseProperty(nameof(Event.EventIdparentNavigation))]
        public virtual ICollection<Event> InverseEventIdparentNavigation { get; set; }

        public ICollection<EventTeam> Teams { get; set; }
    }
}
