// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Heroes.DataAccessLayer.Models
{
    [Table("event_team")]
    public partial class EventTeam
    {
        public EventTeam()
        {
            ReplayCharacterProAssociations = new HashSet<ReplayCharacterProAssociation>();
        }

        [Key]
        public int TeamId { get; set; }
        [Column("EventID", TypeName = "int(11)")]
        public int EventId { get; set; }
        public string Name { get; set; }

        public string LogoUrl { get; set; }

        public Event Event { get; set; }
        [ForeignKey("TeamId")]
        public ICollection<ReplayCharacterProAssociation> ReplayCharacterProAssociations { get; set; }
    }
}
