// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Heroes.DataAccessLayer.Models
{
    [Table("fingerprint_date")]
    public partial class FingerprintDate
    {
        [Column("2017-08-27 14:51:18", TypeName = "datetime")]
        public DateTime? _20170827145118 { get; set; }
        [Column("725ba498-2728-d326-b6ac-11129c55b212", TypeName = "text")]
        public string _725ba4982728D326B6ac11129c55b212 { get; set; }
    }
}