// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Heroes.DataAccessLayer.Models
{
    [Table("groupfinderlisting")]
    public partial class GroupFinderListing
    {
        [Key]
        [Column("PlayerID", TypeName = "int(11)")]
        public int PlayerId { get; set; }
        [Column("GroupFinderListingTypeID", TypeName = "int(11)")]
        public int GroupFinderListingTypeId { get; set; }
        [Required]
        [Column(TypeName = "varchar(200)")]
        public string Information { get; set; }
        [Column("MMRSearchRadius", TypeName = "int(11)")]
        public int MmrsearchRadius { get; set; }
        [Column(TypeName = "timestamp")]
        public DateTime TimestampExpiration { get; set; }

        [ForeignKey(nameof(PlayerId))]
        [InverseProperty("GroupFinderListing")]
        public virtual Player Player { get; set; }
    }
}