// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Heroes.DataAccessLayer.Models
{
    [Table("herotalentinformation")]
    public partial class HeroTalentInformation
    {
        [Key]
        [Column(TypeName = "varchar(50)")]
        public string Character { get; set; }
        [Key]
        [Column(TypeName = "int(11)")]
        public int ReplayBuildFirst { get; set; }
        [Column(TypeName = "int(11)")]
        public int ReplayBuildLast { get; set; }
        [Key]
        [Column("TalentID", TypeName = "int(11)")]
        public int TalentId { get; set; }
        [Column(TypeName = "int(11)")]
        public int TalentTier { get; set; }
        [Required]
        [Column(TypeName = "varchar(50)")]
        public string TalentName { get; set; }
        [Required]
        [Column(TypeName = "varchar(1000)")]
        public string TalentDescription { get; set; }
    }
}