// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Heroes.DataAccessLayer.Models
{
    [Table("leaderboardranking")]
    public partial class LeaderboardRanking
    {
        [Key]
        [Column("PlayerID", TypeName = "int(11)")]
        public int PlayerId { get; set; }
        [Key]
        [Column(TypeName = "int(11)")]
        public int GameMode { get; set; }
        [Column("CurrentMMR", TypeName = "int(11)")]
        public int CurrentMmr { get; set; }
        [Column("LeagueID", TypeName = "int(11)")]
        public int? LeagueId { get; set; }
        [Column(TypeName = "int(11)")]
        public int? LeagueRank { get; set; }
        [Column(TypeName = "bit(1)")]
        public ulong IsEligibleForLeaderboard { get; set; }

        [ForeignKey(nameof(LeagueId))]
        [InverseProperty("LeaderboardRankings")]
        public virtual League League { get; set; }
        [ForeignKey(nameof(PlayerId))]
        [InverseProperty("LeaderboardRankings")]
        public virtual Player Player { get; set; }
    }
}