// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Heroes.DataAccessLayer.Models
{
    [Table("localizationalias")]
    public partial class LocalizationAlias
    {
        public LocalizationAlias()
        {
            PlayerAggregates = new HashSet<PlayerAggregate>();
        }

        [Key]
        [Column("IdentifierID")]
        public int IdentifierId { get; set; }
        public int Type { get; set; }
        [Required]
        [Column(TypeName = "varchar(200)")]
        public string PrimaryName { get; set; }
        [Required]
        [Column(TypeName = "varchar(40)")]
        public string AttributeName { get; set; }
        [Column(TypeName = "varchar(50)")]
        public string Group { get; set; }
        [Column(TypeName = "varchar(50)")]
        public string SubGroup { get; set; }
        [Required]
        [Column("AliasesCSV", TypeName = "varchar(2000)")]
        public string AliasesCsv { get; set; }
        [Column(TypeName = "varchar(50)")]
        public string NewGroup { get; set; }

        [InverseProperty(nameof(PlayerAggregate.FavoriteCharacterNavigation))]
        public virtual ICollection<PlayerAggregate> PlayerAggregates { get; set; }
    }
}