// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Heroes.DataAccessLayer.Models
{
    [Table("logerror")]
    public partial class LogError
    {
        [Key]
        [Column("LogErrorID")]
        public int LogErrorId { get; set; }
        [Required]
        [Column(TypeName = "varchar(500)")]
        public string AbsoluteUri { get; set; }
        [Required]
        [Column(TypeName = "varchar(500)")]
        public string UserAgent { get; set; }
        [Required]
        [Column(TypeName = "varchar(50)")]
        public string UserHostAddress { get; set; }
        [Column("UserID")]
        public int? UserId { get; set; }
        [Required]
        [Column(TypeName = "mediumtext")]
        public string ErrorMessage { get; set; }
        [Column(TypeName = "timestamp")]
        public DateTime DateTimeErrorOccurred { get; set; }
        [Column(TypeName = "varchar(500)")]
        public string Referer { get; set; }

        [ForeignKey(nameof(UserId))]
        [InverseProperty(nameof(Net48User.LogErrors))]
        public virtual Net48User User { get; set; }
    }
}