// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Heroes.DataAccessLayer.Models
{
    [Table("missingtalents")]
    public partial class MissingTalent
    {
        [Key]
        [Column(TypeName = "varchar(50)")]
        public string Character { get; set; }
        [Key]
        [Column(TypeName = "int(11)")]
        public int Build { get; set; }
        [Key]
        [Column("TalentID", TypeName = "int(11)")]
        public int TalentId { get; set; }
    }
}