// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Heroes.DataAccessLayer.Models
{
    [Table("mmrrecalc")]
    public partial class MmrRecalc
    {
        [Key]
        [Column("BattleNetRegionID")]
        public int BattleNetRegionId { get; set; }
        [Key]
        public int GameMode { get; set; }
        [Column(TypeName = "timestamp")]
        public DateTime? TipOld { get; set; }
        [Column(TypeName = "timestamp")]
        public DateTime? TipRecent { get; set; }
        [Column(TypeName = "timestamp")]
        public DateTime? TipManual { get; set; }
    }
}