// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Heroes.DataAccessLayer.Models
{
    [Table("mountinformation")]
    public partial class MountInformation
    {
        [Key]
        [Column(TypeName = "varchar(4)")]
        public string AttributeId { get; set; }
        [Required]
        [Column(TypeName = "varchar(100)")]
        public string Name { get; set; }
        [Required]
        [Column(TypeName = "varchar(1000)")]
        public string Description { get; set; }
        [Required]
        [Column(TypeName = "varchar(50)")]
        public string Franchise { get; set; }
        [Column(TypeName = "date")]
        public DateTime ReleaseDate { get; set; }
    }
}