// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Heroes.DataAccessLayer.Models
{
    [Table("playerbanned")]
    public partial class PlayerBanned
    {
        [Key]
        [Column("PlayerID", TypeName = "int(11)")]
        public int PlayerId { get; set; }

        [ForeignKey(nameof(PlayerId))]
        [InverseProperty("PlayerBanned")]
        public virtual Player Player { get; set; }
    }
}