// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Heroes.DataAccessLayer.Models
{
    [Table("playermmrmilestonev3")]
    public partial class PlayerMmrMilestoneV3
    {
        [Key]
        [Column("PlayerID", TypeName = "int(11)")]
        public int PlayerId { get; set; }
        [Key]
        [Column(TypeName = "int(11)")]
        public int GameMode { get; set; }
        [Key]
        [Column(TypeName = "date")]
        public DateTime MilestoneDate { get; set; }
        [Column("MMRMean")]
        public double Mmrmean { get; set; }
        [Column("MMRStandardDeviation")]
        public double MmrstandardDeviation { get; set; }
        [Column("MMRRating", TypeName = "int(11)")]
        public int Mmrrating { get; set; }

        [ForeignKey(nameof(PlayerId))]
        [InverseProperty("PlayerMmrMilestoneV3s")]
        public virtual Player Player { get; set; }
    }
}