// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Heroes.DataAccessLayer.Models
{
    [Table("playermmrreset")]
    public partial class PlayerMmrReset
    {
        [Key]
        [Column(TypeName = "date")]
        public DateTime ResetDate { get; set; }
        [Required]
        [Column(TypeName = "varchar(50)")]
        public string Title { get; set; }
        [Column("MMRMeanMultiplier")]
        public double MmrmeanMultiplier { get; set; }
        [Column("MMRStandardDeviationGapMultiplier")]
        public double MmrstandardDeviationGapMultiplier { get; set; }
        [Column(TypeName = "bit(1)")]
        public ulong IsClampOutliers { get; set; }
    }
}