// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Heroes.DataAccessLayer.Models
{
    [Table("playeralt")]
    public partial class PlayerAlt
    {
        [Key]
        [Column("PlayerIDAlt", TypeName = "int(11)")]
        public int PlayerIdalt { get; set; }
        [Column("PlayerIDMain", TypeName = "int(11)")]
        public int PlayerIdmain { get; set; }

        [ForeignKey(nameof(PlayerIdalt))]
        [InverseProperty(nameof(Player.PlayerAltPlayerIdaltNavigation))]
        public virtual Player PlayerIdaltNavigation { get; set; }
        [ForeignKey(nameof(PlayerIdmain))]
        [InverseProperty(nameof(Player.PlayerAltPlayerIdmainNavigations))]
        public virtual Player PlayerIdmainNavigation { get; set; }
    }
}