// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Heroes.DataAccessLayer.Models
{
    [Table("playeraggregate")]
    public partial class PlayerAggregate
    {
        [Key]
        [Column("PlayerID", TypeName = "int(11)")]
        public int PlayerId { get; set; }
        [Key]
        [Column(TypeName = "int(11)")]
        public int GameMode { get; set; }
        [Column(TypeName = "int(11)")]
        public int GamesPlayedTotal { get; set; }
        [Column("GamesPlayedWithMMR", TypeName = "int(11)")]
        public int GamesPlayedWithMmr { get; set; }
        [Column(TypeName = "int(11)")]
        public int GamesPlayedRecently { get; set; }
        [Column(TypeName = "int(11)")]
        public int FavoriteCharacter { get; set; }
        [Column(TypeName = "timestamp")]
        public DateTime TimestampLastUpdated { get; set; }

        [ForeignKey(nameof(FavoriteCharacter))]
        [InverseProperty(nameof(LocalizationAlias.PlayerAggregates))]
        public virtual LocalizationAlias FavoriteCharacterNavigation { get; set; }
        [ForeignKey(nameof(PlayerId))]
        [InverseProperty("PlayerAggregates")]
        public virtual Player Player { get; set; }
    }
}