// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Heroes.DataAccessLayer.Models
{
    [Table("premiumpayment")]
    public partial class PremiumPayment
    {
        [Key]
        [Column("TransactionID", TypeName = "varchar(50)")]
        public string TransactionId { get; set; }
        [Required]
        [Column(TypeName = "varchar(128)")]
        public string Email { get; set; }
        [Required]
        [Column(TypeName = "varchar(200)")]
        public string ItemTitle { get; set; }
        [Column(TypeName = "decimal(15,4)")]
        public decimal PaymentAmountGross { get; set; }
        [Column(TypeName = "decimal(15,4)")]
        public decimal PaymentAmountFee { get; set; }
        [Column(TypeName = "timestamp")]
        public DateTime TimestampPayment { get; set; }
    }
}