// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Heroes.DataAccessLayer.Models
{
    [Table("replayteamheroban")]
    public partial class ReplayTeamHeroBan
    {
        [Key]
        [Column("ReplayID", TypeName = "int(11)")]
        public int ReplayId { get; set; }
        [Key]
        [Column("CharacterID", TypeName = "int(11)")]
        public int CharacterId { get; set; }
        [Column(TypeName = "bit(1)")]
        public ulong IsWinner { get; set; }
        [Column(TypeName = "int(11)")]
        public int BanPhase { get; set; }

        [ForeignKey(nameof(ReplayId))]
        [InverseProperty("ReplayTeamHeroBans")]
        public virtual Replay Replay { get; set; }
    }
}