// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Heroes.DataAccessLayer.Models
{
    [Table("replay_dups2")]
    public partial class ReplayDups2
    {
        [Key]
        [Column("ReplayID", TypeName = "int(11)")]
        public int ReplayId { get; set; }
        [Column("DupOfReplayID", TypeName = "int(11)")]
        public int DupOfReplayId { get; set; }
    }
}