// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Heroes.DataAccessLayer.Models
{
    [Table("replaycharactersilenced")]
    public partial class ReplayCharacterSilenced
    {
        [Key]
        [Column("ReplayID", TypeName = "int(11)")]
        public int ReplayId { get; set; }
        [Key]
        [Column("PlayerID", TypeName = "int(11)")]
        public int PlayerId { get; set; }

        [ForeignKey("ReplayId,PlayerId")]
        [InverseProperty("ReplayCharacterSilenced")]
        public virtual ReplayCharacter ReplayCharacter { get; set; }
    }
}