// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Heroes.DataAccessLayer.Models
{
    [Table("replaycharacter")]
    public partial class ReplayCharacter
    {
        public ReplayCharacter()
        {
            ReplayCharacterMatchAwards = new HashSet<ReplayCharacterMatchAward>();
            ReplayCharacterTalents = new HashSet<ReplayCharacterTalent>();
            ReplayCharacterUpgradeEventReplayLengthPercents = new HashSet<ReplayCharacterUpgradeEventReplayLengthPercent>();
        }

        [Key]
        [Column("ReplayID", TypeName = "int(11)")]
        public int ReplayId { get; set; }
        [Key]
        [Column("PlayerID", TypeName = "int(11)")]
        public int PlayerId { get; set; }
        [Column(TypeName = "bit(1)")]
        public ulong IsAutoSelect { get; set; }
        [Column("CharacterID", TypeName = "int(11)")]
        public int CharacterId { get; set; }
        [Column(TypeName = "int(11)")]
        public int CharacterLevel { get; set; }
        [Column(TypeName = "bit(1)")]
        public ulong IsWinner { get; set; }
        [Column("MMRBefore", TypeName = "int(11)")]
        public int? Mmrbefore { get; set; }
        [Column("MMRChange", TypeName = "int(11)")]
        public int? Mmrchange { get; set; }

        [ForeignKey(nameof(PlayerId))]
        [InverseProperty("ReplayCharacters")]
        public virtual Player Player { get; set; }
        [ForeignKey(nameof(ReplayId))]
        [InverseProperty("ReplayCharacters")]
        public virtual Replay Replay { get; set; }
        [InverseProperty("ReplayCharacter")]
        public virtual ReplayCharacterDraftOrder ReplayCharacterDraftOrder { get; set; }
        [InverseProperty("ReplayCharacter")]
        public virtual ReplayCharacterScoreResult ReplayCharacterScoreResult { get; set; }
        [InverseProperty("ReplayCharacter")]
        public virtual ReplayCharacterSilenced ReplayCharacterSilenced { get; set; }
        [InverseProperty(nameof(ReplayCharacterMatchAward.ReplayCharacter))]
        public virtual ICollection<ReplayCharacterMatchAward> ReplayCharacterMatchAwards { get; set; }
        [InverseProperty(nameof(Heroes.DataAccessLayer.Models.ReplayCharacterProAssociation.ReplayCharacter))]
        public virtual ReplayCharacterProAssociation ReplayCharacterProAssociation { get; set; }
        [InverseProperty(nameof(ReplayCharacterTalent.ReplayCharacter))]
        public virtual ICollection<ReplayCharacterTalent> ReplayCharacterTalents { get; set; }
        [InverseProperty(nameof(ReplayCharacterUpgradeEventReplayLengthPercent.ReplayCharacter))]
        public virtual ICollection<ReplayCharacterUpgradeEventReplayLengthPercent> ReplayCharacterUpgradeEventReplayLengthPercents { get; set; }
    }
}