// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Heroes.DataAccessLayer.Models
{
    [Table("replaycharactertalent")]
    public partial class ReplayCharacterTalent
    {
        [Key]
        [Column("ReplayID", TypeName = "int(11)")]
        public int ReplayId { get; set; }
        [Key]
        [Column("PlayerID", TypeName = "int(11)")]
        public int PlayerId { get; set; }
        [Key]
        [Column("TalentID", TypeName = "int(11)")]
        public int TalentId { get; set; }

        [ForeignKey(nameof(PlayerId))]
        [InverseProperty("ReplayCharacterTalents")]
        public virtual Player Player { get; set; }
        [ForeignKey(nameof(ReplayId))]
        [InverseProperty("ReplayCharacterTalents")]
        public virtual Replay Replay { get; set; }
        [ForeignKey("ReplayId,PlayerId")]
        [InverseProperty("ReplayCharacterTalents")]
        public virtual ReplayCharacter ReplayCharacter { get; set; }
    }
}