// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Heroes.DataAccessLayer.Models
{
    [Table("replaycharacterdraftorder")]
    public partial class ReplayCharacterDraftOrder
    {
        [Key]
        [Column("ReplayID")]
        public int ReplayId { get; set; }
        [Key]
        [Column("PlayerID")]
        public int PlayerId { get; set; }
        public int DraftOrder { get; set; }

        [ForeignKey(nameof(PlayerId))]
        [InverseProperty("ReplayCharacterDraftOrders")]
        public virtual Player Player { get; set; }
        [ForeignKey(nameof(ReplayId))]
        [InverseProperty("ReplayCharacterDraftOrders")]
        public virtual Replay Replay { get; set; }
        [ForeignKey("ReplayId,PlayerId")]
        [InverseProperty("ReplayCharacterDraftOrder")]
        public virtual ReplayCharacter ReplayCharacter { get; set; }
    }
}