// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Heroes.DataAccessLayer.Models
{
    [Table("replayperiodicxpbreakdown")]
    public partial class ReplayPeriodicXpBreakdown
    {
        [Key]
        [Column("ReplayID", TypeName = "int(11)")]
        public int ReplayId { get; set; }
        [Key]
        [Column(TypeName = "bit(1)")]
        public ulong IsWinner { get; set; }
        [Key]
        [Column(TypeName = "int(11)")]
        public int GameTimeMinute { get; set; }
        [Column("MinionXP", TypeName = "int(11)")]
        public int MinionXp { get; set; }
        [Column("CreepXP", TypeName = "int(11)")]
        public int CreepXp { get; set; }
        [Column("StructureXP", TypeName = "int(11)")]
        public int StructureXp { get; set; }
        [Column("HeroXP", TypeName = "int(11)")]
        public int HeroXp { get; set; }
        [Column("TrickleXP", TypeName = "int(11)")]
        public int TrickleXp { get; set; }

        [ForeignKey(nameof(ReplayId))]
        [InverseProperty("ReplayPeriodicXpBreakdowns")]
        public virtual Replay Replay { get; set; }
    }
}