// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Heroes.DataAccessLayer.CustomModels;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Heroes.DataAccessLayer.Models
{
    [Table("replaycharacterscoreresult")]
    public partial class ReplayCharacterScoreResult
    {
        [Key]
        [Column("ReplayID", TypeName = "int(11)")]
        public int ReplayId { get; set; }
        [Key]
        [Column("PlayerID", TypeName = "int(11)")]
        public int PlayerId { get; set; }
        [Column(TypeName = "int(11)")]
        public int? Level { get; set; }
        [Column(TypeName = "int(11)")]
        public int Takedowns { get; set; }
        [Column(TypeName = "int(11)")]
        public int SoloKills { get; set; }
        [Column(TypeName = "int(11)")]
        public int Assists { get; set; }
        [Column(TypeName = "int(11)")]
        public int Deaths { get; set; }
        [Column(TypeName = "int(11)")]
        public int? HighestKillStreak { get; set; }
        [Column(TypeName = "int(11)")]
        public int HeroDamage { get; set; }
        [Column(TypeName = "int(11)")]
        public int SiegeDamage { get; set; }
        [Column(TypeName = "int(11)")]
        public int StructureDamage { get; set; }
        [Column(TypeName = "int(11)")]
        public int MinionDamage { get; set; }
        [Column(TypeName = "int(11)")]
        public int CreepDamage { get; set; }
        [Column(TypeName = "int(11)")]
        public int SummonDamage { get; set; }
        [Column("TimeCCdEnemyHeroes", TypeName = "time")]
        public TimeSpan? TimeCcdEnemyHeroes { get; set; }
        [Column(TypeName = "int(11)")]
        public int? Healing { get; set; }
        [Column(TypeName = "int(11)")]
        public int SelfHealing { get; set; }
        [Column(TypeName = "int(11)")]
        public int? DamageTaken { get; set; }
        [Column(TypeName = "int(11)")]
        public int ExperienceContribution { get; set; }
        [Column(TypeName = "int(11)")]
        public int TownKills { get; set; }
        [Column(TypeName = "time")]
        public TimeSpan TimeSpentDead { get; set; }
        [Column(TypeName = "int(11)")]
        public int MercCampCaptures { get; set; }
        [Column(TypeName = "int(11)")]
        public int WatchTowerCaptures { get; set; }
        [Column(TypeName = "int(11)")]
        public int MetaExperience { get; set; }

        [ForeignKey("ReplayId,PlayerId")]
        [InverseProperty("ReplayCharacterScoreResult")]
        public virtual ReplayCharacter ReplayCharacter { get; set; }
    }
}