// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Heroes.DataAccessLayer.Models
{
    [Table("replaycharacterupgradeeventreplaylengthpercent")]
    public partial class ReplayCharacterUpgradeEventReplayLengthPercent
    {
        [Key]
        [Column("ReplayID", TypeName = "int(11)")]
        public int ReplayId { get; set; }
        [Key]
        [Column("PlayerID", TypeName = "int(11)")]
        public int PlayerId { get; set; }
        [Key]
        [Column(TypeName = "int(11)")]
        public int UpgradeEventType { get; set; }
        [Key]
        [Column(TypeName = "int(11)")]
        public int UpgradeEventValue { get; set; }
        [Column(TypeName = "decimal(15,13)")]
        public decimal ReplayLengthPercent { get; set; }

        [ForeignKey("ReplayId,PlayerId")]
        [InverseProperty("ReplayCharacterUpgradeEventReplayLengthPercents")]
        public virtual ReplayCharacter ReplayCharacter { get; set; }
    }
}