// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Heroes.DataAccessLayer.Models
{
    [Table("replaycharacter_pro_association")]
    public partial class ReplayCharacterProAssociation
    {
        [Column("ReplayID", TypeName = "int(11)")]
        public int ReplayId { get; set; }
        [Column("PlayerID", TypeName = "int(11)")]
        public int PlayerId { get; set; }

        public int? TeamId { get; set; }
        public string ProName { get; set; }

        [ForeignKey(nameof(PlayerId))]
        [InverseProperty("ReplayCharacterProAssociations")]
        public virtual Player Player { get; set; }
        [ForeignKey(nameof(ReplayId))]
        [InverseProperty("ReplayCharacterProAssociations")]
        public virtual Replay Replay { get; set; }
        [ForeignKey("ReplayId,PlayerId")]
        [InverseProperty("ReplayCharacterProAssociation")]
        public virtual ReplayCharacter ReplayCharacter { get; set; }

        public EventTeam Team { get; set; }
    }
}
