// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Heroes.DataAccessLayer.Models
{
    [Table("replayshare")]
    public partial class ReplayShare
    {
        [Key]
        [Column("ReplayShareID", TypeName = "int(11)")]
        public int ReplayShareId { get; set; }
        [Column("ReplayID", TypeName = "int(11)")]
        public int ReplayId { get; set; }
        [Column("PlayerIDSharedBy", TypeName = "int(11)")]
        public int PlayerIdsharedBy { get; set; }
        [Required]
        [Column(TypeName = "varchar(200)")]
        public string AlteredReplayFileName { get; set; }
        [Required]
        [Column(TypeName = "varchar(200)")]
        public string Title { get; set; }
        [Required]
        [Column(TypeName = "mediumtext")]
        public string Description { get; set; }
        [Column(TypeName = "int(11)")]
        public int UpvoteScore { get; set; }

        [ForeignKey(nameof(PlayerIdsharedBy))]
        [InverseProperty(nameof(Player.ReplayShares))]
        public virtual Player PlayerIdsharedByNavigation { get; set; }
        [ForeignKey(nameof(ReplayId))]
        [InverseProperty("ReplayShares")]
        public virtual Replay Replay { get; set; }
    }
}