// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Heroes.DataAccessLayer.Models
{
    [Table("reputation")]
    public partial class Reputation
    {
        [Key]
        public int PlayerId { get; set; }
        [Column("Reputation")]
        public int Reputation1 { get; set; }

        [ForeignKey(nameof(PlayerId))]
        [InverseProperty("Reputation")]
        public virtual Player Player { get; set; }
    }
}