// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Heroes.DataAccessLayer.Models
{
    [Table("talentimagemapping")]
    public partial class TalentImageMapping
    {
        [Key]
        [Column(TypeName = "varchar(45)")]
        public string TalentName { get; set; }
        [Column(TypeName = "varchar(255)")]
        public string TalentImage { get; set; }
        [Key]
        [Column(TypeName = "varchar(50)")]
        public string HeroName { get; set; }
        [Column(TypeName = "varchar(45)")]
        public string Character { get; set; }
    }
}