// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Heroes.DataAccessLayer.Models
{
    [Table("tournament_participant")]
    public partial class TournamentParticipant
    {
        [Key]
        public int ParticipantId { get; set; }
        public int TournamentId { get; set; }
        public int TeamId { get; set; }
        public string Battletag { get; set; }
    }
}
