// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Heroes.DataAccessLayer.Models
{
    [Table("tournament_team")]
    public partial class TournamentTeamDB
    {
        [Key]
        public int TeamId { get; set; }
        public int TournamentId { get; set; }
        public string TeamName { get; set; }
        public string CaptainEmail { get; set; }
        public int IsPaid { get; set; }
        public string PaypalEmail { get; set; }
        public DateTime RegistrationDate { get; set; }
    }
}
