// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Heroes.DataAccessLayer.Models
{
    [Table("zamuser")]
    public partial class ZamUser
    {
        [Key]
        [Column("ID", TypeName = "varchar(36)")]
        public string Id { get; set; }
        [Required]
        [Column(TypeName = "varchar(128)")]
        public string Email { get; set; }
        [Required]
        [Column(TypeName = "varchar(100)")]
        public string Username { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? PremiumExpiration { get; set; }
        [Column(TypeName = "int(11)")]
        public int? IsHotslogsPremiumConverted { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime TimestampCreated { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime TimestampLastUpdated { get; set; }
    }
}