export interface MatchDetails {
    Heroes: string[],
    TeamObjectiveNames: string[],
    TeamObjectiveImages: string[],
    XValues: number[],
    YValues: number[],
    XHeroDeaths: number[],
    YHeroDeaths: number[],
    XDiff: number[],
    YDiff: number[],
    MatchEventTimers: number[],
    DeathTimers: number[],
    EventLabels: string[],
    DeathLabels: string[],
    MaxXpDifference: number,
    TeamObjectiveStyles: string[],
    HeroDeathStyles: string[],
    MaxXpDiffTick: number,
}
